#!/usr/local/bin/perl

use strict;
use warnings;

use Astro::App::Satpass2;
use Getopt::Long;

my %opt;
GetOptions(\%opt, qw{gmt location=s}) or die <<eod;
The only valid options are
 -gmt
   causes output times to be in GMT;
 -location command
   executes the given command before displaying the almanac; this
   command is presumably a macro to set your location.
eod

my @args = ('-filter');
my $time = join ' ', map {
    (my $s = $_) =~ s/([\\'])/\\$1/g; $s} @ARGV;
$opt{location} and push @args, $opt{location};
push @args, 'location', 'echo', "almanac '$time'", 'echo',
    "quarters '$time'", 'exit';

Astro::App::Satpass2->run(@args);
